import type { Metadata } from "next";
import "./globals.css";
import {
  NavigationMenu,
  NavigationMenuItem,
  NavigationMenuList,
} from "@/components/ui/navigation-menu";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body>
        <header className="bg-green-700 text-white py-4">
          <div className="container mx-auto flex justify-between items-center">
            <div className="text-2xl font-bold">Cristo Rei Implementos</div>
            <NavigationMenu>
              <NavigationMenuList className="flex space-x-4">
                <NavigationMenuItem>
                  <Link href="/" className="text-white hover:text-green-200">
                    Home
                  </Link>
                </NavigationMenuItem>
                <NavigationMenuItem>
                  <Link
                    href="/contato"
                    className="text-white hover:text-green-200"
                  >
                    Contato
                  </Link>
                </NavigationMenuItem>
              </NavigationMenuList>
            </NavigationMenu>
          </div>
        </header>

        <main>{children}</main>

        <footer className="bg-green-800 text-white py-8">
          <div className="container mx-auto text-center">
            © 2023 - {new Date().getFullYear()} | Cristo Rei Implementos. Todos os
            direitos reservados.
          </div>
          <div className="container mx-auto text-center">
            Desenvolvido por Leonardo Cintra - <Link target="_blank" href={"https://x.com/leonardoncintra"}>@leonardoncintra</Link> 
          </div>
        </footer>
      </body>
    </html>
  );
}
